### ISSUE TITLE
How to check online player level?

### ISSUE THREAD

**Issue by farson2020** [BloodDragon2580/Palguard#1]
Thank you for sharing a perfect solution that will bring more player interaction to Palworld
I want to query and display player data on Discord Bot,
Is there any relevant rcon command that can output player level or other data?

**Comment by BloodDragon2580** [comment]
Palguard is not from me i make only the german support and share the files on github for easy installing.

But to your question, no sorry not at this time.

**Comment by farson2020** [comment]
Thanks for your reply
